"""Shared constants for CogA."""

MODEL_VERSION = "CogA-1.0-pro"
CONTRACT_VERSION = "1.0"
SCHEMA_VERSION = "1.0"
DEFAULT_REASONING_PACK_ID = "default"
MAX_OPTIONS = 5
MAX_CLARIFICATIONS = 1
MAX_OBSERVATIONS = 1
